Update metadata-extraction.yml

diff --git a/.github/workflows/metadata-extraction.yml b/.github/workflows/metadata-extraction.yml
--- a/.github/workflows/metadata-extraction.yml
+++ b/.github/workflows/metadata-extraction.yml
@@ -29,15 +29,18 @@ jobs:
 
     - name: Run Metadata Extraction Script
       run: python lib/library_and_pages_x.py
-      
+
+    - name: Pull latest changes from the repository
+      run: git pull --rebase  # Using rebase to avoid a merge commit
+
     - name: Commit and Push Changes
       run: |
         git config --global user.name 'Mischlichter'
         git config --global user.email 'alex.stephan.weimar@web.de'
         git add lib/metadata.json
-        git add docs/sharing/*.html  # Add this line to include HTML files
+        git add docs/sharing/*.html
         git add docs/sharing/*_favicon.ico
-        echo "Waiting for 2 minute before committing and pushing..."
-        sleep 71  # Wait for 1 minute
+        echo "Waiting for 1 minute before committing and pushing..."
+        sleep 60  # Wait for 1 minute
         git commit -m "Update image metadata, HTML pages, and favicons" || echo "No changes to commit"
-        git push
+        git push || echo "Failed to push changes. Check for potential conflicts or issues."
